### ISSUE TITLE
Mechanism for rebuilding database file from scratch

### ISSUE THREAD

**Issue by simonw** [simonw/scrape-instances-social#5]
Will need this to fix:
- #2 
- #4

**Comment by simonw** [comment]
Can copy this pattern:

https://github.com/simonw/datasette.io/blob/5455068f5ffdb8cd3f09a4d84d94b7512a46b18e/.github/workflows/deploy.yml?q=%22if%3A%22+user%3Asimonw+path%3A.github%2Fworkflows%2F*.yml#L34-L37

```yaml
on:
  workflow_dispatch:
    inputs:
      from_scratch:
        description: Enter 'skip' to create a new database from scratch
```

```yaml
    - name: Download previous content.db
      if: github.event.inputs.from_scratch != 'skip'
      run: |
        curl -O https://datasette.io/content.db
```
